### ISSUE TITLE
Liste des participants

### ISSUE THREAD

**Issue by fraxken** [ES-Community/ludum-dare-45#1]
Cette issue a pour objectif d'avoir une liste des participants avec leurs affinités techniques (merci quand même de préciser si vous êtes certains de participer ou non).

Nous risquons d'être nombreux donc il faut pouvoir s'organiser un minimum à l'avance. Ce qui à été décidé pour le moment:

- Utiliser Electron.js
- Utiliser [Three.js](https://threejs.org/) (ce qui semble le plus complet et nous offrir le plus de possibilités)
- Faire du multijoueur pourrait être une bonne idée surtout si nous sommes beaucoup de développeurs (à voir en brainstorming le moment venue).

En attente de vos commentaires avec:

- Vos dispos (quelques heures / participer avec nous pendant 2 ou 3 jours).
- Vos affinités (plutôt sur le jeu, le back, les interfaces, graphismes, tout ?).

**Comment by fraxken** [comment]
Pour ma part

Dispo: 100% de la jam
Mes affinités: plutôt jeu et back (je fais un peu de pixel art aussi mais rien de dingue).

**Comment by targos** [comment]
Dispo: 100%
Affinités: back, jeu, un peu interface

**Comment by AlexandreMalaj** [comment]
Dispo: 100%
Affinités: Back, jeu, et intéressé de faire de la 3D avec des personnes qui s'y connaissent !

**Comment by Westixy** [comment]
~~Dispo: 2-3jours (dependra du patron)~~
Affinites: Back/electron
EDIT: pas dispo

**Comment by Purexo** [comment]
Pour ceux qui ont la flemme de check les dates :
https://ldjam.com/events/ludum-dare/45

C'est du samedi 5 octobre 00:00 au 8 octobre.

J'aimerai participer, Je suis assez touche à tout niveau dev, pas trop artiste. A voir de ce qui aura besoin à ce moment.

Je vous préviendrez quand j'aurais mes dispo.

PS : Three.js c'est bien. Mais c'est pas un moteur de jeu complet (juste un moteur de rendu 3d), pensez y ;-)

**Comment by CroquetMickael** [comment]
Dispo 100% de la jam
Affinité: Back/Electron me dérange pas de toucher un peu à tout pour aider si besoin.
